### PR TITLE
modifySubroutine

### PR DESCRIPTION
**Pull request by ComLock**
I have not tested the browserEvaluator changes.

Also this should be documented, right?

### CODE REVIEW

**Comment by ComLock** [comment]
In terms of naming things, my thinking was there is already a subroutine and aliases starting with the letter "s", for example "select". So I went with "modify". Since you have gone with "read" rather than "get", "CRUD" comes to mind, so you could rename "modify" to "update". But then again you went with "remove" rather than "delete". So "modify" seems fine to me.

**Comment by ComLock** [comment]
This actually doesn't solve what I'm trying to do, but is still a nice feature?

See
https://github.com/gajus/pianola/issues/5

**Comment by ComLock** [comment]
Sitting on the train home. Upon further consideration I think the modify should take an optional first parameter "selector" and so it can modify multiple elements. It should even be possible to call it before "select"

**Comment by ComLock** [comment]
I think this pull request should be closed and another one opened which simply implements setAttributeValue and setPropertyValue in the evaluators.

Then I can make custom subroutines in my project which accesses those methods via bindle.evaluator.setAttributeValue and bindle.evaluator.setPropertyValue

**Comment by ComLock** [comment]
That way I can implement a subroutine "absolutify" which

1. selects all links below some selector
2. for each link read attribute href
2.1 apply resolve on the value
2.2 setAttributeValue href to the resolved value
3. return the modified dom object

In a html document there are many other places that can contain relative urls, absolutify could cover those too.

**Comment by gajus** [comment]
I have added support for inline subroutines.

It can be used to achieve this functionality.

https://github.com/gajus/surgeon#inline-subroutines

**Pull request closed without merging**
